//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIX_Dejan_Prodanovic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVacationRequest
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FirstDayDate { get; set; }
        public Nullable<System.DateTime> LastDayDate { get; set; }
        public string RequestState { get; set; }
        public string ReasonOfRefuse { get; set; }
        public string ReasonOfDelete { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
